serenity.project.name=SWAG LABS
serenity.test.root=oren.example
serenity.browser.maximized=true
serenity.use.unique.browser=false
serenity.restart.browser.each.scenario=true
webdriver.timeouts.implicitlywait=10000
serenity.timeout=10000
webdriver.driver=chrome
webdriver.autodownload=true
chrome.switches=--headless,--no-sandbox,--disable-dev-shm-usage,--disable-gpu
